export const FRIEND_STATUS_ANONYMOUS = 'FRIEND_STATUS_ANONYMOUS';
export const FRIEND_STATUS_ME = 'FRIEND_STATUS_ME';
export const FRIEND_STATUS_FRIEND = 'FRIEND_STATUS_FRIEND';
export const FRIEND_STATUS_REQUESTER = 'FRIEND_STATUS_REQUESTER';
export const FRIEND_STATUS_ACCEPTER = 'FRIEND_STATUS_ACCEPTER';
